name: inaagapay_flutter_v2
description: "Inaagapay Maternal and Child Health Information System"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Supabase
  supabase_flutter: ^2.5.6

  # Environment variables
  flutter_dotenv: ^5.1.0

  # Date formatting
  intl: ^0.19.0

  # State management
  provider: ^6.1.2

  # HTTP requests
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
